name: genie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
  - assets/images/logo.png
  - assets/images/logo-2.png
  - assets/images/logo-3.png



  fonts:
    - family: sans
      fonts:
        - asset: assets/fonts/sans.ttf

